// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Mabuntle.Infrastructure.Persistence;

#nullable disable

namespace Mabuntle.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MabuntleDbContext))]
    [Migration("20260518172239_AiProductModeration")]
    partial class AiProductModeration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mabuntle")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "mabuntle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "mabuntle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "mabuntle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "mabuntle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "mabuntle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Admin.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("text");

                    b.Property<string>("PreviousValueJson")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiModerationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedTermsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detected_terms_json");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags_json");

                    b.Property<string>("MissingFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_fields_json");

                    b.Property<bool>("NeedsAdminReview")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NeedsAdminReview");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("ai_moderation_results", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiProductSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputImageIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_image_ids_json");

                    b.Property<string>("InputNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MissingFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_fields_json");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("QualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("RiskFlagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_flags_json");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SuggestedAttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_attributes_json");

                    b.Property<Guid?>("SuggestedCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestedCategoryPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SuggestedFullDescription")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("SuggestedShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SuggestedTagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_tags_json");

                    b.Property<string>("SuggestedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.ToTable("ai_product_suggestions", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiPromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureName", "Version")
                        .IsUnique();

                    b.ToTable("ai_prompt_versions", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiSuggestionFieldAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_value");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SellerFinalValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("seller_final_value");

                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasEdited")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.ToTable("ai_suggestion_field_audits", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostEstimate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("InputTokenEstimate")
                        .HasColumnType("integer");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("OutputTokenEstimate")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FeatureName");

                    b.HasIndex("SellerId");

                    b.HasIndex("UserId");

                    b.ToTable("ai_usage_logs", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Buyers.BuyerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("buyer_profiles", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId", "DisplayOrder");

                    b.ToTable("categories", "mabuntle");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Women",
                            Slug = "women"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Clothing",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Slug = "women-clothing"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Dresses",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Slug = "women-clothing-dresses"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Tops",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Slug = "women-clothing-tops"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Men",
                            Slug = "men"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Clothing",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Slug = "men-clothing"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Shirts",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Slug = "men-clothing-shirts"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            DisplayOrder = 30,
                            IsActive = true,
                            Name = "Jewellery",
                            Slug = "jewellery"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Earrings",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Slug = "jewellery-earrings"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Hoop Earrings",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Slug = "jewellery-earrings-hoop-earrings"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Rings",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Slug = "jewellery-rings"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            DisplayOrder = 40,
                            IsActive = true,
                            Name = "Accessories",
                            Slug = "accessories"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Bags",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000012"),
                            Slug = "accessories-bags"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Belts",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000012"),
                            Slug = "accessories-belts"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            DisplayOrder = 50,
                            IsActive = true,
                            Name = "Beauty",
                            Slug = "beauty"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Makeup",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000015"),
                            Slug = "beauty-makeup"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Foundation",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000016"),
                            Slug = "beauty-makeup-foundation"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Skincare",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000015"),
                            Slug = "beauty-skincare"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Cleansers",
                            ParentCategoryId = new Guid("20000000-0000-0000-0000-000000000018"),
                            Slug = "beauty-skincare-cleansers"
                        });
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.CategoryAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values_json");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "DisplayOrder");

                    b.HasIndex("CategoryId", "Key")
                        .IsUnique();

                    b.ToTable("category_attributes", "mabuntle");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AllowedValuesJson = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000003"),
                            DataType = "Select",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "size",
                            Name = "Size"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000003"),
                            DataType = "Text",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = true,
                            Key = "colour",
                            Name = "Colour"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000003"),
                            DataType = "Text",
                            DisplayOrder = 30,
                            IsActive = true,
                            IsRequired = false,
                            Key = "material",
                            Name = "Material"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AllowedValuesJson = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000004"),
                            DataType = "Select",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "size",
                            Name = "Size"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000004"),
                            DataType = "Text",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = true,
                            Key = "colour",
                            Name = "Colour"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            AllowedValuesJson = "[\"S\",\"M\",\"L\",\"XL\",\"XXL\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000007"),
                            DataType = "Select",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "size",
                            Name = "Size"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000007"),
                            DataType = "Text",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = true,
                            Key = "colour",
                            Name = "Colour"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000007"),
                            DataType = "Text",
                            DisplayOrder = 30,
                            IsActive = true,
                            IsRequired = false,
                            Key = "fit",
                            Name = "Fit"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            AllowedValuesJson = "[\"Gold\",\"Silver\",\"Stainless Steel\",\"Beaded\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000010"),
                            DataType = "Select",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "material",
                            Name = "Material"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000010"),
                            DataType = "Text",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = false,
                            Key = "colour",
                            Name = "Colour"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            AllowedValuesJson = "[\"Gold\",\"Silver\",\"Stainless Steel\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000011"),
                            DataType = "Select",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "material",
                            Name = "Material"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            AllowedValuesJson = "[\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000011"),
                            DataType = "Select",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = true,
                            Key = "ring-size",
                            Name = "Ring Size"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            AllowedValuesJson = "[\"Leather\",\"Vegan Leather\",\"Canvas\",\"Fabric\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000013"),
                            DataType = "Select",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "material",
                            Name = "Material"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000013"),
                            DataType = "Text",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = true,
                            Key = "colour",
                            Name = "Colour"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            AllowedValuesJson = "[\"S\",\"M\",\"L\",\"XL\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000014"),
                            DataType = "Select",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "size",
                            Name = "Size"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            AllowedValuesJson = "[\"Leather\",\"Vegan Leather\",\"Fabric\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000014"),
                            DataType = "Select",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = true,
                            Key = "material",
                            Name = "Material"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000017"),
                            DataType = "Text",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "shade",
                            Name = "Shade"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            AllowedValuesJson = "[\"Dry\",\"Oily\",\"Combination\",\"Sensitive\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000017"),
                            DataType = "MultiSelect",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = false,
                            Key = "skin-type",
                            Name = "Skin Type"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000017"),
                            DataType = "Decimal",
                            DisplayOrder = 30,
                            IsActive = true,
                            IsRequired = false,
                            Key = "volume-ml",
                            Name = "Volume ml"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            AllowedValuesJson = "[\"Dry\",\"Oily\",\"Combination\",\"Sensitive\"]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000019"),
                            DataType = "MultiSelect",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = true,
                            Key = "skin-type",
                            Name = "Skin Type"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000021"),
                            AllowedValuesJson = "[]",
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000019"),
                            DataType = "Decimal",
                            DisplayOrder = 20,
                            IsActive = true,
                            IsRequired = false,
                            Key = "volume-ml",
                            Name = "Volume ml"
                        });
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags_json");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status");

                    b.HasIndex("SellerId", "Slug")
                        .IsUnique()
                        .HasFilter("\"Slug\" IS NOT NULL");

                    b.ToTable("products", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Key")
                        .IsUnique();

                    b.ToTable("product_attribute_values", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.HasIndex("ProductId", "SortOrder");

                    b.ToTable("product_images", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ProductId", "Sku")
                        .IsUnique();

                    b.HasIndex("ProductId", "Size", "Colour")
                        .IsUnique();

                    b.ToTable("product_variants", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.ToTable("seller_addresses", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerPayoutProfilePlaceholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasSubmittedPlaceholder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdminApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("PayoutProviderReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.ToTable("seller_payout_profiles", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("seller_profiles", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerStorefront", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("seller_storefronts", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("seller_verifications", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "mabuntle");
                });

            modelBuilder.Entity("Mabuntle.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "mabuntle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Mabuntle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Mabuntle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mabuntle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Mabuntle.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiModerationResult", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiProductSuggestion", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiSuggestionFieldAudit", b =>
                {
                    b.HasOne("Mabuntle.Domain.Ai.AiProductSuggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Ai.AiUsageLog", b =>
                {
                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Mabuntle.Domain.Buyers.BuyerProfile", b =>
                {
                    b.HasOne("Mabuntle.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Mabuntle.Domain.Buyers.BuyerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.Category", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.CategoryAttribute", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.ProductAttributeValue", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("Mabuntle.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerAddress", b =>
                {
                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithOne()
                        .HasForeignKey("Mabuntle.Domain.Sellers.SellerAddress", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerPayoutProfilePlaceholder", b =>
                {
                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithOne()
                        .HasForeignKey("Mabuntle.Domain.Sellers.SellerPayoutProfilePlaceholder", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerProfile", b =>
                {
                    b.HasOne("Mabuntle.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Mabuntle.Domain.Sellers.SellerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerStorefront", b =>
                {
                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithOne()
                        .HasForeignKey("Mabuntle.Domain.Sellers.SellerStorefront", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Domain.Sellers.SellerVerification", b =>
                {
                    b.HasOne("Mabuntle.Domain.Sellers.SellerProfile", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mabuntle.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Mabuntle.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
