// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Swyftly.Infrastructure.Persistence;

#nullable disable

namespace Swyftly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SwyftlyDbContext))]
    [Migration("20260529122130_BuyerGrowthDiscoveryTelemetry")]
    partial class BuyerGrowthDiscoveryTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mabuntle")
                .HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
